corpus_file: AGNews-world-tech.h5
categories:
  - World
  - Tech
kw_file: AGNews-world-tech
seed_words:
  - political
  - technology
model_file: agnews_model
# parameter for Java
train_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/train/'
test_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/test/'
label_matrix_path: /Users/admin/dataless-classification/error-estimation/label_matrices/
label_matrix_file: AGNews-world-tech
raw_keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/
keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/ge_exp/
keyword_files:  # each file contains a different set of keywords. one line per category, keywords are space-deliminated
  - AGNews-world-tech-seed
  - AGNews-world-tech-all
  - AGNews-world-tech-manual
  - AGNews-world-tech-ours
  - AGNews-world-tech-ours-new
