corpus_file: AGNews-business-sports.h5
categories:
  - Business
  - Sports
kw_file: AGNews-business-sports
seed_words:
  - business
  - sports
model_file: agnews_model
# parameter for Java
train_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/train/'
test_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/test/'
label_matrix_path: /Users/admin/dataless-classification/error-estimation/label_matrices/
label_matrix_file: AGNews-business-sports
raw_keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/
keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/ge_exp/
keyword_files:  # each file contains a different set of keywords. one line per category, keywords are space-deliminated
  - AGNews-business-sports-seed
  - AGNews-business-sports-all
  - AGNews-business-sports-manual
  - AGNews-business-sports-ours
