corpus_file: AGNews-world-sports.h5
categories:
  - World
  - Sports
kw_file: AGNews-world-sports
seed_words:
  - minister
  - sports
model_file: agnews_model
# parameter for Java
train_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/train/'
test_corpus_path: '/Users/admin/corpora/TextClassification/AG News Corpus/test/'
label_matrix_path: /Users/admin/dataless-classification/error-estimation/label_matrices/
label_matrix_file: AGNews-world-sports
raw_keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/
keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/ge_exp/
keyword_files:  # each file contains a different set of keywords. one line per category, keywords are space-deliminated
  - AGNews-world-sports-0
  - AGNews-world-sports-1
  - AGNews-world-sports-2
  - AGNews-world-sports-3
  - AGNews-world-sports-final
