corpus_file: nyt.h5
categories:
  - movies
  - television
kw_file: NYT-movies-television
seed_words:
  - movie
  - television
model_file: nyt_model
# parameter for Java
train_corpus_path: /Users/admin/corpora/TextClassification/nyt/train/
test_corpus_path: /Users/admin/corpora/TextClassification/nyt/test/
label_matrix_path: /Users/admin/dataless-classification/error-estimation/label_matrices/
label_matrix_file: NYT-movies-television
raw_keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/
keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/ge_exp/
keyword_files:  # each file contains a different set of keywords. one line per category, keywords are space-deliminated
  - NYT-movies-television-seed
  - NYT-movies-television-all
  - NYT-movies-television-manual
  - NYT-movies-television-ours
  - NYT-movies-television-ours-new