corpus_file: nyt.h5
categories:
  - international_business
  - economy
kw_file: NYT-international_business-economy
seed_words:
  - business
  - economy
model_file: nyt_model
# parameter for Java
train_corpus_path: /Users/admin/corpora/TextClassification/nyt/train/
test_corpus_path: /Users/admin/corpora/TextClassification/nyt/test/
label_matrix_path: /Users/admin/dataless-classification/error-estimation/label_matrices/
label_matrix_file: NYT-international_business-economy
raw_keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/
keyword_path: /Users/admin/dataless-classification/error-estimation/noisy_keywords/ge_exp/
keyword_files:  # each file contains a different set of keywords. one line per category, keywords are space-deliminated
  - NYT-international_business-economy-seed
  - NYT-international_business-economy-all
  - NYT-international_business-economy-manual
  - NYT-international_business-economy-ours
  - NYT-international_business-economy-ours-new
  - NYT-international_business-economy-ours-rerun